# Generated by Django 4.1 on 2022-08-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.IntegerField()),
                ('notify_date', models.DateField()),
                ('is_notified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='no_of_files',
            field=models.IntegerField(default=0),
        ),
    ]
