# Generated by Django 4.1 on 2022-08-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vns', '0002_categories_doctype_notification_document_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
