# Generated by Django 4.1 on 2022-09-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vns', '0003_document_doc_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docu_id', models.IntegerField()),
                ('filepath', models.CharField(max_length=250)),
            ],
        ),
    ]
