# Generated by Django 4.1 on 2022-09-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vns', '0004_fileuploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('transactdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
