# Generated by Django 4.1 on 2022-09-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vns', '0005_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='transactdate',
            field=models.DateTimeField(),
        ),
    ]
