# Generated by Django 4.1 on 2022-09-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vns', '0006_alter_wallet_transactdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('ad_name', models.CharField(max_length=50)),
                ('ad_title', models.CharField(max_length=50)),
                ('ad_content', models.CharField(max_length=100)),
                ('ad_link', models.CharField(max_length=100)),
                ('ad_type', models.CharField(max_length=50)),
                ('noOfClicks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InAppAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('ad_id1', models.IntegerField(default=0)),
                ('ad_id2', models.IntegerField(default=0)),
                ('ad_id3', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NotifyAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('ad_id1', models.IntegerField(default=0)),
                ('ad_id2', models.IntegerField(default=0)),
                ('ad_id3', models.IntegerField(default=0)),
            ],
        ),
    ]
