# Generated by Django 4.1 on 2022-09-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vns', '0008_walletbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletbalance',
            name='total_ads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='walletbalance',
            name='total_spend',
            field=models.IntegerField(default=0),
        ),
    ]
