# Generated by Django 4.1 on 2022-09-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vns', '0011_advertisement_publish_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='amount_spend',
            field=models.IntegerField(default=0),
        ),
    ]
